[package]
name = "mp"
version = "0.1.0"
edition = "2021"
description = "Venus macro processor."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
